name: Trigger auto deployment for hf-fastapi-app

on:
  workflow_dispatch: # Allows you to click "Run workflow" manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to GHCR
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:latest
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy or Update Azure Container App
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            
            # Check if the container app already exists from a previous run
            if az containerapp show --name hf-fastapi-app --resource-group hf-deployment-rg &>/dev/null; then
              echo "App exists. Updating with the newly built image..."
              az containerapp update \
                --name hf-fastapi-app \
                --resource-group hf-deployment-rg \
                --image ghcr.io/${{ env.REPO }}:latest
            else
              echo "App does not exist yet. Provisioning it fresh..."
              az containerapp create \
                --name hf-fastapi-app \
                --resource-group hf-deployment-rg \
                --environment hf-env \
                --image ghcr.io/${{ env.REPO }}:latest \
                --target-port 80 \
                --ingress external \
                --cpu "2.0" \
                --memory "4.0Gi" \
                --registry-server "ghcr.io" \
                --registry-username "${{ github.actor }}" \
                --registry-password "${{ secrets.CR_PAT }}"
            fi
